import type { BlogPost } from './posts'

export const POSTS_PART_1: BlogPost[] = [
  {
    slug: 'meta-ads-leads-qualificados',
    title: 'Meta Ads: como gerar leads qualificados (e não só curtidas)',
    description:
      'Guia prático de Meta Ads para gerar leads qualificados: estrutura de campanha, públicos, criativos e integração com CRM para medir o que realmente importa — vendas.',
    category: 'Meta Ads',
    author: 'Equipe Althos',
    date: '2026-05-20',
    readingMinutes: 7,
    excerpt:
      'Anunciar no Facebook e Instagram é fácil. Difícil é transformar cliques em clientes. Veja como estruturar campanhas de Meta Ads focadas em leads que realmente compram.',
    blocks: [
      { type: 'p', text: 'Investir em Meta Ads sem um processo de qualificação é como abrir a torneira sem ter onde guardar a água. Você gera volume, mas perde a maior parte no caminho. Neste guia, você vai entender como estruturar campanhas para atrair leads qualificados e, principalmente, como medir o que importa: vendas, não curtidas.' },
      { type: 'h2', text: 'Comece pelo objetivo certo' },
      { type: 'p', text: 'O erro mais comum é escolher o objetivo de campanha errado. Se você quer leads, não otimize para "engajamento" ou "alcance". Use objetivos de "Cadastros" (formulário instantâneo) ou "Vendas" com conversões rastreadas. O algoritmo da Meta entrega para quem tem maior probabilidade de realizar a ação que você otimiza.' },
      { type: 'h2', text: 'Estruture a campanha em 3 camadas' },
      { type: 'ol', items: [
        'Topo (frio): públicos amplos e interesses. Objetivo de gerar reconhecimento e capturar os primeiros leads.',
        'Meio (morno): remarketing de quem engajou com vídeos, visitou o site ou abriu o formulário sem concluir.',
        'Fundo (quente): remarketing de quem demonstrou intenção clara. Aqui o custo por lead é menor e a conversão é maior.',
      ] },
      { type: 'h2', text: 'Públicos que funcionam' },
      { type: 'ul', items: [
        'Públicos semelhantes (lookalike) a partir da sua base de clientes — quanto melhor a base, melhor o público.',
        'Remarketing de visitantes do site e de quem interagiu no Instagram/Facebook.',
        'Interesses combinados com comportamento de compra, testados um de cada vez.',
      ] },
      { type: 'h2', text: 'Criativos: pare o scroll e qualifique' },
      { type: 'p', text: 'O criativo é onde a qualificação começa. Uma headline específica ("Consultoria para clínicas que querem lotar a agenda") filtra naturalmente quem não é seu público. Use prova social, mostre o resultado e deixe claro para quem é. Teste pelo menos 3 variações por conjunto.' },
      { type: 'h2', text: 'O elo perdido: integração com o CRM' },
      { type: 'p', text: 'Aqui está o que separa quem desperdiça verba de quem escala. Quando os leads do Meta Ads caem direto no seu CRM, com a origem identificada por campanha, você consegue responder em segundos e medir quais campanhas geram vendas — não só leads.' },
      { type: 'quote', text: 'Um lead respondido em até 5 minutos tem até 9x mais chance de converter do que um respondido depois de 30 minutos.' },
      { type: 'p', text: 'No Althos CRM, cada lead do Meta Ads chega com a origem da campanha, é atendido automaticamente por IA 24h e entra no funil. No fim do mês, você vê exatamente qual campanha trouxe receita — e corta o que não funciona.' },
      { type: 'cta', text: 'Conecte seus anúncios ao funil e meça vendas, não curtidas.' },
    ],
  },
  // ───────────────────────────────────────────────────────────────────────────
  {
    slug: 'como-montar-funil-de-vendas',
    title: 'Como montar um funil de vendas que converte (passo a passo)',
    description:
      'Aprenda a montar um funil de vendas do zero: etapas, critérios de avanço, follow-up e métricas. Um guia prático para parar de perder leads por desorganização.',
    category: 'Funil de Vendas',
    author: 'Equipe Althos',
    date: '2026-05-14',
    readingMinutes: 8,
    excerpt:
      'A maioria das vendas é perdida não por falta de leads, mas por falta de processo. Veja como estruturar um funil que conduz o cliente da primeira conversa ao fechamento.',
    blocks: [
      { type: 'p', text: 'Funil de vendas é a representação visual da jornada que um lead percorre desde o primeiro contato até virar cliente. Sem ele, sua equipe vende no improviso: esquece de retornar, não sabe em que pé está cada negociação e perde oportunidades por puro descontrole.' },
      { type: 'h2', text: 'As etapas essenciais de um funil' },
      { type: 'p', text: 'Não existe funil universal, mas a maioria dos negócios funciona bem com estas etapas. Adapte ao seu ciclo de venda:' },
      { type: 'ol', items: [
        'Novo lead: acabou de chegar, ainda não foi contatado.',
        'Em contato: você já iniciou a conversa e está qualificando.',
        'Qualificado: o lead tem perfil, interesse e poder de decisão.',
        'Proposta enviada: a oferta está na mesa.',
        'Negociação: ajustes finais, objeções, condições.',
        'Fechado (ganho/perdido): o desfecho — e sempre registre o motivo da perda.',
      ] },
      { type: 'h2', text: 'Defina critérios claros de avanço' },
      { type: 'p', text: 'O maior erro em funis é mover o lead "no feeling". Cada etapa precisa de um critério objetivo de entrada. Por exemplo: só vai para "Qualificado" quem confirmou orçamento e prazo. Isso evita um funil inflado de oportunidades que nunca vão fechar.' },
      { type: 'h2', text: 'Follow-up: onde as vendas acontecem' },
      { type: 'p', text: 'Estudos mostram que a maioria das vendas exige vários contatos, mas grande parte dos vendedores desiste no primeiro "não". Um bom funil tem follow-up programado em cada etapa — e o ideal é que ele seja automático.' },
      { type: 'ul', items: [
        'Lead parado há 2 dias em "Em contato"? Dispare uma mensagem automática.',
        'Proposta enviada e sem resposta há 3 dias? Crie uma tarefa de retorno.',
        'Negócio perdido? Programe uma reativação em 90 dias.',
      ] },
      { type: 'h2', text: 'Métricas que mostram a saúde do funil' },
      { type: 'ul', items: [
        'Taxa de conversão por etapa: onde os leads travam?',
        'Tempo médio em cada etapa: onde está o gargalo?',
        'Motivos de perda: o que mais derruba suas vendas?',
        'Previsão de receita: quanto há no funil ponderado pela probabilidade.',
      ] },
      { type: 'quote', text: 'O que não é medido não é gerenciado. Um funil sem métricas é só uma lista de tarefas bonita.' },
      { type: 'p', text: 'No Althos CRM, o funil é visual e arrastável, com indicadores de tempo parado, leads em risco e previsão de receita automática. Você vê o gargalo na hora e age antes de perder a venda.' },
      { type: 'cta', text: 'Monte seu funil visual e pare de perder leads por desorganização.' },
    ],
  },
  // ───────────────────────────────────────────────────────────────────────────
  {
    slug: 'sdr-closer-cs-estrutura-time-vendas',
    title: 'SDR, Closer e CS: como estruturar um time de vendas que escala',
    description:
      'Entenda os papéis de SDR, Closer e Customer Success, quando contratar cada um e como treiná-los. O modelo de time de vendas que permite escalar com previsibilidade.',
    category: 'Treinamento de Vendas',
    author: 'Equipe Althos',
    date: '2026-05-08',
    readingMinutes: 9,
    excerpt:
      'Vendedor que faz tudo sozinho é gargalo. Separar prospecção, fechamento e pós-venda em papéis especializados é o que permite escalar. Veja como estruturar.',
    blocks: [
      { type: 'p', text: 'Conforme a operação cresce, o "vendedor faz-tudo" vira o maior gargalo do negócio. A solução que empresas de alto crescimento adotaram é simples: especializar. Cada etapa da venda passa a ter um responsável. Vamos aos três papéis fundamentais.' },
      { type: 'h2', text: 'SDR — o especialista em prospecção e qualificação' },
      { type: 'p', text: 'O SDR (Sales Development Representative) é responsável pelo topo do funil: fazer o primeiro contato, qualificar o lead e agendar a reunião para o closer. Ele não fecha vendas — ele entrega oportunidades quentes e bem qualificadas.' },
      { type: 'ul', items: [
        'Responde leads rapidamente (velocidade é tudo no topo).',
        'Aplica critérios de qualificação (perfil, dor, orçamento, decisor).',
        'Agenda reuniões e passa o contexto completo para o closer.',
      ] },
      { type: 'h2', text: 'Closer — o especialista em fechamento' },
      { type: 'p', text: 'O closer recebe leads já qualificados e foca no que faz de melhor: conduzir a negociação, lidar com objeções e fechar. Como ele só fala com quem tem real intenção, sua taxa de conversão é muito maior do que a de um vendedor que prospecta e fecha ao mesmo tempo.' },
      { type: 'h3', text: 'Por que separar SDR e closer funciona' },
      { type: 'p', text: 'Prospecção e fechamento exigem perfis e energias diferentes. Quem fica o dia todo recebendo "nãos" na prospecção raramente está no melhor estado para uma negociação delicada. Separar protege o foco e a performance de cada um.' },
      { type: 'h2', text: 'CS — o especialista em retenção e expansão' },
      { type: 'p', text: 'O Customer Success (CS) entra depois da venda. Sua missão é garantir que o cliente tenha resultado, reduzir cancelamentos e gerar novas vendas (upsell e indicações). Em negócios recorrentes, o CS costuma ser o papel com maior impacto no faturamento de longo prazo.' },
      { type: 'h2', text: 'Quando contratar cada papel' },
      { type: 'ol', items: [
        'Comece com vendedores full-cycle (fazem tudo) enquanto o volume é baixo.',
        'Contrate o primeiro SDR quando a prospecção começar a roubar o tempo de fechamento.',
        'Estruture o CS quando a retenção e o pós-venda passarem a definir o crescimento.',
      ] },
      { type: 'h2', text: 'O treinamento que faz a diferença' },
      { type: 'ul', items: [
        'Scripts e playbooks por etapa (abordagem, qualificação, objeções).',
        'Role-play semanal: treinar a venda antes de fazê-la com o cliente real.',
        'Revisão de gravações e métricas individuais para feedback objetivo.',
      ] },
      { type: 'quote', text: 'Time especializado sem processo registrado é talento desperdiçado. O CRM é onde o playbook vira execução.' },
      { type: 'p', text: 'No Althos CRM, SDRs qualificam com a ajuda da IA, closers recebem leads com todo o histórico e o time de CS acompanha clientes e reativações — tudo com papéis, permissões e ranking de produtividade.' },
      { type: 'cta', text: 'Dê ao seu time a estrutura para vender com previsibilidade.' },
    ],
  },
  // ───────────────────────────────────────────────────────────────────────────
  {
    slug: 'google-ads-ou-meta-ads',
    title: 'Google Ads ou Meta Ads: qual escolher para o seu negócio?',
    description:
      'Google Ads x Meta Ads: as diferenças de intenção, custo e funil. Entenda quando usar cada um (ou os dois) e como medir o retorno real de cada canal.',
    category: 'Google Ads',
    author: 'Equipe Althos',
    date: '2026-05-02',
    readingMinutes: 6,
    excerpt:
      'Não é uma guerra: é uma questão de momento e intenção. Veja a diferença entre demanda capturada e demanda gerada — e como decidir onde investir.',
    blocks: [
      { type: 'p', text: 'A pergunta "Google Ads ou Meta Ads?" aparece em toda reunião de marketing. A resposta honesta é: depende do tipo de demanda que você quer atingir. Entender essa diferença economiza muito dinheiro.' },
      { type: 'h2', text: 'Google Ads: captura demanda existente' },
      { type: 'p', text: 'Quem pesquisa "dentista em São Paulo" ou "CRM para imobiliária" já está procurando. O Google Ads coloca você na frente dessa pessoa no momento exato da intenção. O custo por clique tende a ser mais alto, mas a intenção é maior — ótimo para fundo de funil.' },
      { type: 'ul', items: [
        'Ideal quando já existe procura ativa pelo seu produto/serviço.',
        'Alta intenção: o lead já sabe o que quer.',
        'Excelente para serviços locais e buscas específicas.',
      ] },
      { type: 'h2', text: 'Meta Ads: gera demanda nova' },
      { type: 'p', text: 'No Facebook e Instagram, as pessoas não estão procurando você — estão rolando o feed. O Meta Ads é imbatível para gerar interesse em quem ainda não sabia que precisava da sua solução. Custo por lead menor, mas exige mais qualificação e nutrição.' },
      { type: 'ul', items: [
        'Ideal para criar demanda e alcançar quem ainda não procura.',
        'Forte em segmentação por perfil, interesses e comportamento.',
        'Ótimo para topo e meio de funil, com remarketing poderoso.',
      ] },
      { type: 'h2', text: 'A resposta na maioria dos casos: os dois' },
      { type: 'p', text: 'Meta Ads gera a demanda e aquece o público; Google Ads captura quem passou a procurar pela sua marca ou solução. Juntos, cobrem a jornada inteira. A decisão de por onde começar depende do seu orçamento e do quanto já existe de procura pelo que você vende.' },
      { type: 'h2', text: 'O que realmente define o vencedor: medição' },
      { type: 'p', text: 'De nada adianta debater canais se você não mede qual deles gera venda. Sem origem rastreada no CRM, você decide no escuro. Com ela, descobre que — por exemplo — o Google traz menos leads, mas converte o dobro; ou que o Meta enche o funil que o Google fecha.' },
      { type: 'quote', text: 'O melhor canal é aquele que, no seu CRM, mostra o menor custo por venda — não por clique ou por lead.' },
      { type: 'p', text: 'No Althos CRM, cada lead carrega a origem da campanha, e os relatórios mostram custo por venda por canal. Você para de adivinhar e passa a investir onde o retorno é real.' },
      { type: 'cta', text: 'Meça o retorno real de cada canal direto no seu funil.' },
    ],
  },
  // ───────────────────────────────────────────────────────────────────────────
  {
    slug: 'gestao-equipe-vendas-metricas',
    title: 'Gestão de equipe de vendas: 7 métricas que todo gestor deve acompanhar',
    description:
      'As 7 métricas essenciais para gerir um time de vendas com clareza: conversão, ciclo de venda, ticket médio, atividades, follow-up, taxa de no-show e ranking.',
    category: 'Gestão de Equipe',
    author: 'Equipe Althos',
    date: '2026-04-25',
    readingMinutes: 7,
    excerpt:
      'Gerir vendas no "achismo" custa caro. Estas 7 métricas transformam sua gestão em decisão baseada em dados — e mostram exatamente onde agir.',
    blocks: [
      { type: 'p', text: 'Gerir uma equipe de vendas sem métricas é dirigir olhando só pelo retrovisor. Você sabe o que já aconteceu (o faturamento do mês), mas não consegue agir a tempo. As 7 métricas a seguir dão visão de presente e futuro.' },
      { type: 'h2', text: '1. Taxa de conversão por etapa' },
      { type: 'p', text: 'Não basta saber a conversão geral. Veja em qual etapa os leads travam. Se muita gente entra como "qualificado" mas poucos chegam a "proposta", o problema está na abordagem comercial, não na geração de leads.' },
      { type: 'h2', text: '2. Ciclo de venda' },
      { type: 'p', text: 'Quanto tempo, em média, um lead leva do primeiro contato ao fechamento? Ciclos que aumentam sem explicação indicam gargalos no processo ou leads cada vez menos qualificados.' },
      { type: 'h2', text: '3. Ticket médio' },
      { type: 'p', text: 'O valor médio por venda. Acompanhar por vendedor revela quem vende mais barato (e poderia subir) e quem domina vendas maiores (e poderia treinar os demais).' },
      { type: 'h2', text: '4. Atividades por vendedor' },
      { type: 'p', text: 'Ligações, mensagens, reuniões. Resultado é consequência de atividade. Quando alguém está abaixo da meta, o número de atividades quase sempre explica antes de qualquer outra coisa.' },
      { type: 'h2', text: '5. Taxa de follow-up' },
      { type: 'p', text: 'Quantos leads recebem o retorno programado? Essa é a métrica mais negligenciada e a que mais dinheiro deixa na mesa. Automatizar o follow-up costuma ser o ajuste de maior impacto imediato.' },
      { type: 'h2', text: '6. Taxa de no-show' },
      { type: 'p', text: 'Em operações com reuniões e agendamentos, faltas matam a produtividade. Lembretes automáticos por WhatsApp reduzem drasticamente o no-show.' },
      { type: 'h2', text: '7. Ranking e produtividade individual' },
      { type: 'p', text: 'Comparar performance de forma transparente cria saudável competição e revela quem precisa de apoio. Mas só funciona com dados confiáveis — registrados, não estimados.' },
      { type: 'quote', text: 'Gestão de vendas é 80% processo e 20% inspiração. As métricas são o termômetro do processo.' },
      { type: 'p', text: 'No Althos CRM, todas essas métricas aparecem em dashboards automáticos, com ranking de vendedores, previsão de receita e alertas de leads em risco. O gestor para de cobrar planilha e passa a agir sobre o que importa.' },
      { type: 'cta', text: 'Tenha as métricas da sua equipe em tempo real, sem planilha.' },
    ],
  },
  // ─── META ADS ──────────────────────────────────────────────────────────────
  {
    slug: 'meta-ads-publico-lookalike',
    title: 'Público semelhante (lookalike) no Meta Ads: o guia definitivo',
    description:
      'Como criar públicos semelhantes (lookalike) no Meta Ads que realmente convertem: qual base usar, percentual ideal e como combinar com remarketing.',
    category: 'Meta Ads',
    author: 'Equipe Althos',
    date: '2026-05-22',
    readingMinutes: 6,
    excerpt:
      'O público semelhante é a arma mais subutilizada do Meta Ads. O segredo não está na ferramenta, mas na qualidade da base que você entrega ao algoritmo.',
    blocks: [
      { type: 'p', text: 'O público semelhante (lookalike) pega uma lista sua — clientes, leads quentes, compradores — e pede à Meta para encontrar pessoas parecidas. Bem usado, é a forma mais barata de escalar leads qualificados. Mal usado, é só queima de verba.' },
      { type: 'h2', text: 'Tudo começa pela base de origem' },
      { type: 'p', text: 'O algoritmo só é tão bom quanto a lista que você dá a ele. Um lookalike de "todos que visitaram o site" é fraco. Um lookalike de "clientes que compraram acima do ticket médio" é ouro. Quanto mais específica e valiosa a base, melhor o público gerado.' },
      { type: 'ul', items: [
        'Melhor base: clientes que realmente compraram (idealmente os de maior valor).',
        'Boa base: leads qualificados que avançaram no funil.',
        'Base fraca: lista genérica de visitantes ou seguidores.',
      ] },
      { type: 'h2', text: 'Qual percentual escolher (1% a 10%)' },
      { type: 'p', text: 'O percentual define o tamanho e a precisão. 1% é o público mais parecido com a sua base (mais qualificado, menor alcance). 5% a 10% amplia o alcance, mas dilui a semelhança. Comece em 1%–2% e suba conforme precisar de volume.' },
      { type: 'h2', text: 'Combine lookalike com remarketing' },
      { type: 'p', text: 'Lookalike preenche o topo do funil com gente nova e parecida com seus melhores clientes. O remarketing recupera quem já interagiu. Rodar os dois em conjunto cobre desde a descoberta até o fechamento.' },
      { type: 'quote', text: 'Um lookalike só é tão inteligente quanto a base que você alimenta. Lixo entra, lixo sai.' },
      { type: 'p', text: 'No Althos CRM, sua base de clientes fica organizada e segmentada, pronta para exportar como base de origem dos seus melhores públicos semelhantes — e você ainda mede quais campanhas trazem os clientes de maior valor.' },
      { type: 'cta', text: 'Transforme sua base de clientes nos melhores públicos do Meta Ads.' },
    ],
  },
  {
    slug: 'meta-ads-criativos-que-convertem',
    title: 'Criativos de Meta Ads que convertem: a anatomia do anúncio que vende',
    description:
      'O que faz um criativo de Meta Ads converter: gancho, prova, oferta e CTA. Estrutura prática, formatos que funcionam e como testar variações.',
    category: 'Meta Ads',
    author: 'Equipe Althos',
    date: '2026-05-16',
    readingMinutes: 6,
    excerpt:
      'No Meta Ads, o criativo é 80% do resultado. Veja a anatomia de um anúncio que para o scroll, qualifica e gera lead — e como testar do jeito certo.',
    blocks: [
      { type: 'p', text: 'Com a automatização da segmentação, o criativo virou a principal alavanca de performance no Meta Ads. É ele quem para o scroll, comunica a oferta e filtra quem é (ou não) seu público. Vamos à anatomia de um criativo que converte.' },
      { type: 'h2', text: '1. Gancho: os 3 primeiros segundos' },
      { type: 'p', text: 'Se o início não prende, nada mais importa. Comece com a dor do cliente, uma pergunta direta ou um resultado surpreendente. Em vídeo, mostre movimento e fala nos primeiros segundos. No estático, uma headline forte e visual contrastante.' },
      { type: 'h2', text: '2. Prova: por que acreditar em você' },
      { type: 'ul', items: [
        'Depoimentos reais de clientes.',
        'Números e resultados concretos.',
        'Antes e depois, prints de conversas, casos.',
      ] },
      { type: 'h2', text: '3. Oferta clara e para quem é' },
      { type: 'p', text: 'Diga exatamente o que a pessoa ganha e para quem aquilo serve. Especificidade qualifica: "para clínicas que querem lotar a agenda" afasta quem não é público e atrai quem é.' },
      { type: 'h2', text: '4. CTA: o próximo passo óbvio' },
      { type: 'p', text: 'Um único pedido claro: "Chame no WhatsApp", "Preencha o formulário", "Agende uma avaliação". Mais de um CTA confunde e derruba a conversão.' },
      { type: 'h2', text: 'Como testar sem desperdiçar' },
      { type: 'p', text: 'Teste uma variável por vez: mude só o gancho, depois só a oferta. Rode pelo menos 3 variações por conjunto e dê tempo de a Meta otimizar antes de julgar. E o teste de verdade não termina no clique.' },
      { type: 'quote', text: 'Um criativo que gera muitos leads ruins é pior do que um que gera poucos leads bons.' },
      { type: 'p', text: 'No Althos CRM, você vê quais criativos trazem leads que viram venda — não só os que geram cliques baratos. Assim, escala o que dá lucro e corta o que só infla métrica.' },
      { type: 'cta', text: 'Descubra quais criativos trazem clientes, não só cliques.' },
    ],
  },
  {
    slug: 'meta-ads-orcamento-quanto-investir',
    title: 'Quanto investir em Meta Ads? Como definir o orçamento certo',
    description:
      'Como definir o orçamento de Meta Ads sem chutar: cálculo por meta de vendas, CPL, fase de aprendizado e quando escalar a verba com segurança.',
    category: 'Meta Ads',
    author: 'Equipe Althos',
    date: '2026-05-10',
    readingMinutes: 6,
    excerpt:
      '"Quanto devo investir em anúncios?" A resposta não é um número mágico — é uma conta. Veja como calcular o orçamento a partir da sua meta de vendas.',
    blocks: [
      { type: 'p', text: 'A pergunta certa não é "quanto gastar", e sim "quanto preciso investir para bater minha meta". Orçamento de tráfego é cálculo, não palpite. Vamos à conta.' },
      { type: 'h2', text: 'Comece pela meta, não pela verba' },
      { type: 'ol', items: [
        'Defina quantas vendas você quer no mês.',
        'Use sua taxa de conversão de lead para venda para descobrir quantos leads precisa.',
        'Multiplique pelos leads pelo seu custo por lead (CPL) estimado.',
      ] },
      { type: 'p', text: 'Exemplo: meta de 10 vendas, conversão de 20% (logo, 50 leads), CPL de R$ 30 = R$ 1.500 de investimento mínimo. Sem saber sua conversão real, você chuta — e por isso o CRM é parte da conta.' },
      { type: 'h2', text: 'Respeite a fase de aprendizado' },
      { type: 'p', text: 'A Meta precisa de volume de conversões para otimizar (a famosa fase de aprendizado). Orçamentos muito baixos nunca saem dela, e o desempenho fica instável. Garanta verba suficiente para gerar conversões consistentes por semana.' },
      { type: 'h2', text: 'Quando (e como) escalar' },
      { type: 'ul', items: [
        'Escale quando o custo por venda estiver dentro do que é lucrativo para você.',
        'Aumente a verba em incrementos (20%–30%) para não reiniciar o aprendizado.',
        'Antes de escalar, garanta que o time dá conta do volume de leads.',
      ] },
      { type: 'quote', text: 'Não existe orçamento certo sem saber seu custo por venda. E custo por venda só existe com CRM.' },
      { type: 'p', text: 'No Althos CRM você acompanha CPL, taxa de conversão e custo por venda por campanha. Com esses números, definir e escalar o orçamento deixa de ser aposta e vira decisão.' },
      { type: 'cta', text: 'Saiba exatamente quanto investir para bater sua meta de vendas.' },
    ],
  },
  {
    slug: 'meta-ads-remarketing-que-vende',
    title: 'Remarketing no Meta Ads: como recuperar quem quase comprou',
    description:
      'Estratégias de remarketing no Meta Ads para recuperar leads que demonstraram interesse: segmentação por etapa, criativos e frequência ideal.',
    category: 'Meta Ads',
    author: 'Equipe Althos',
    date: '2026-05-04',
    readingMinutes: 5,
    excerpt:
      'A maioria das pessoas não compra no primeiro contato. O remarketing é o que recupera esse interesse — e costuma ser a verba de melhor retorno na conta.',
    blocks: [
      { type: 'p', text: 'Remarketing é mostrar anúncios para quem já interagiu com você: visitou o site, assistiu ao vídeo, abriu o formulário, conversou no direct. Como essas pessoas já conhecem sua marca, o custo por resultado costuma ser o menor da conta.' },
      { type: 'h2', text: 'Segmente por nível de interesse' },
      { type: 'ul', items: [
        'Quente: abandonou o checkout ou abriu o formulário sem concluir.',
        'Morno: visitou páginas-chave ou interagiu várias vezes.',
        'Frio recente: viu um vídeo ou seguiu o perfil.',
      ] },
      { type: 'p', text: 'Cada nível merece uma mensagem diferente. Quem quase comprou precisa de um empurrão (oferta, urgência). Quem só assistiu a um vídeo precisa de mais prova e contexto.' },
      { type: 'h2', text: 'Criativos de remarketing que funcionam' },
      { type: 'ul', items: [
        'Depoimentos para quebrar a objeção final.',
        'Respostas às dúvidas mais comuns.',
        'Oferta com prazo para gerar decisão.',
      ] },
      { type: 'h2', text: 'Cuidado com a frequência' },
      { type: 'p', text: 'Remarketing repetido demais irrita e queima a marca. Monitore a frequência e renove os criativos para não cansar o público.' },
      { type: 'quote', text: 'O remarketing recupera o interesse online. O follow-up no CRM recupera a venda.' },
      { type: 'p', text: 'No Althos CRM, o lead que voltou pelo remarketing é atendido na hora e entra no funil com follow-up automático. Anúncio reacende o interesse; o processo fecha a venda.' },
      { type: 'cta', text: 'Recupere quem quase comprou com anúncio e follow-up no mesmo fluxo.' },
    ],
  },
]
