import type { BlogPost } from './posts'

export const POSTS_PART_2: BlogPost[] = [
  {
    slug: 'meta-ads-erros-comuns',
    title: '7 erros em Meta Ads que estão queimando sua verba',
    description:
      'Os erros mais comuns em Meta Ads que desperdiçam dinheiro: objetivo errado, público estreito, mexer cedo demais e não medir vendas. Veja como evitar.',
    category: 'Meta Ads',
    author: 'Equipe Althos',
    date: '2026-04-28',
    readingMinutes: 6,
    excerpt:
      'Se seus anúncios não dão retorno, provavelmente é um destes 7 erros. A boa notícia: todos têm solução simples.',
    blocks: [
      { type: 'p', text: 'Meta Ads não perdoa erro de estrutura: o algoritmo simplesmente gasta sua verba do jeito errado. Veja os sete deslizes mais comuns e como corrigi-los.' },
      { type: 'h2', text: '1. Escolher o objetivo errado' },
      { type: 'p', text: 'Otimizar para "engajamento" quando se quer venda entrega curtidas, não clientes. Escolha o objetivo alinhado ao resultado que importa.' },
      { type: 'h2', text: '2. Público estreito demais' },
      { type: 'p', text: 'Empilhar interesses até sobrar pouca gente impede o algoritmo de aprender. Dê espaço para a Meta encontrar quem converte.' },
      { type: 'h2', text: '3. Mexer cedo demais' },
      { type: 'p', text: 'Pausar ou editar antes do fim da fase de aprendizado reinicia tudo. Dê tempo e volume antes de julgar.' },
      { type: 'h2', text: '4. Um único criativo' },
      { type: 'p', text: 'Sem variações, não há o que otimizar. Rode pelo menos três criativos por conjunto.' },
      { type: 'h2', text: '5. Ignorar o remarketing' },
      { type: 'p', text: 'Rodar só público frio é deixar dinheiro na mesa. Quem já interagiu converte mais barato.' },
      { type: 'h2', text: '6. Não responder rápido' },
      { type: 'p', text: 'Gerar lead e demorar horas para responder mata a conversão. Velocidade é parte da campanha.' },
      { type: 'h2', text: '7. Não medir vendas' },
      { type: 'p', text: 'O pior de todos: olhar CPL e cliques, mas não saber quais campanhas geram receita. Sem isso, você otimiza para a métrica errada.' },
      { type: 'quote', text: 'O anúncio gera o lead. O que acontece depois define se a verba virou lucro ou prejuízo.' },
      { type: 'p', text: 'No Althos CRM, leads chegam com origem rastreada, atendimento automático em segundos e relatório de custo por venda. Você evita os erros 6 e 7 — os que mais doem no bolso.' },
      { type: 'cta', text: 'Pare de queimar verba: meça do clique até a venda.' },
    ],
  },
  // ─── GOOGLE ADS ────────────────────────────────────────────────────────────
  {
    slug: 'google-ads-palavras-chave',
    title: 'Palavras-chave no Google Ads: como escolher as que trazem clientes',
    description:
      'Guia de palavras-chave para Google Ads: tipos de correspondência, intenção de compra, palavras negativas e como evitar gastar com cliques que não vendem.',
    category: 'Google Ads',
    author: 'Equipe Althos',
    date: '2026-05-18',
    readingMinutes: 7,
    excerpt:
      'No Google Ads, a palavra-chave é a aposta. Escolher errado é pagar por cliques de curiosos. Veja como mirar quem está pronto para comprar.',
    blocks: [
      { type: 'p', text: 'No Google Ads você paga para aparecer quando alguém pesquisa. A palavra-chave define quem vê seu anúncio — e é por isso que ela faz ou quebra a campanha. O objetivo: atrair intenção de compra, não curiosidade.' },
      { type: 'h2', text: 'Entenda a intenção por trás da busca' },
      { type: 'ul', items: [
        'Alta intenção: "comprar", "preço", "contratar", "perto de mim".',
        'Pesquisa/comparação: "melhor", "x ou y", "vale a pena".',
        'Informacional: "como fazer", "o que é" — raramente compra agora.',
      ] },
      { type: 'p', text: 'Para vender já, priorize alta intenção. Termos informacionais servem para topo de funil e conteúdo, não para campanhas de conversão direta.' },
      { type: 'h2', text: 'Tipos de correspondência' },
      { type: 'ol', items: [
        'Ampla: maior alcance, menor controle — gaste com cautela.',
        'De frase: equilíbrio entre alcance e relevância.',
        'Exata: máximo controle, ideal para os termos campeões.',
      ] },
      { type: 'h2', text: 'Palavras negativas: o filtro que economiza' },
      { type: 'p', text: 'Tão importante quanto escolher palavras é excluir as erradas. Se você vende serviço pago, negative "grátis", "download", "vaga de emprego". Palavras negativas evitam cliques que nunca virariam cliente.' },
      { type: 'quote', text: 'Cada clique de curioso é dinheiro que não volta. Palavras negativas são o seu filtro de qualidade.' },
      { type: 'p', text: 'No Althos CRM, você vê quais palavras-chave geraram leads que viraram venda. Em vez de otimizar por clique, otimiza por receita — e descobre que poucos termos trazem a maior parte do faturamento.' },
      { type: 'cta', text: 'Descubra quais palavras-chave realmente trazem clientes.' },
    ],
  },
  {
    slug: 'google-ads-primeira-campanha-passo-a-passo',
    title: 'Como criar sua primeira campanha no Google Ads (passo a passo)',
    description:
      'Tutorial para criar a primeira campanha de pesquisa no Google Ads: estrutura de conta, grupos de anúncios, textos, extensões e acompanhamento de conversão.',
    category: 'Google Ads',
    author: 'Equipe Althos',
    date: '2026-05-12',
    readingMinutes: 8,
    excerpt:
      'Um passo a passo claro para lançar sua primeira campanha de pesquisa no Google Ads sem cair nas armadilhas que custam caro para iniciantes.',
    blocks: [
      { type: 'p', text: 'Criar uma campanha no Google Ads é simples; criar uma que dá retorno exige estrutura. Veja o caminho do começo ao fim, evitando os erros que fazem iniciantes queimarem verba.' },
      { type: 'h2', text: '1. Estruture a conta corretamente' },
      { type: 'p', text: 'Pense em camadas: a campanha define orçamento e objetivo; dentro dela, grupos de anúncios reúnem palavras-chave de um mesmo tema. Um grupo focado significa anúncios mais relevantes e custo menor.' },
      { type: 'h2', text: '2. Comece com campanha de Pesquisa' },
      { type: 'p', text: 'Para a maioria dos negócios, a Rede de Pesquisa é o melhor ponto de partida: você aparece para quem já procura sua solução. Deixe Display e Performance Max para depois de dominar o básico.' },
      { type: 'h2', text: '3. Agrupe palavras por tema' },
      { type: 'ul', items: [
        'Um grupo por serviço/produto, com 5–15 palavras relacionadas.',
        'Anúncios que repetem a palavra-chave do grupo no título.',
        'Use correspondência de frase e exata para começar com controle.',
      ] },
      { type: 'h2', text: '4. Escreva anúncios relevantes' },
      { type: 'p', text: 'Repita o termo buscado no título, destaque o diferencial e termine com um CTA claro. Quanto mais o anúncio "responde" à busca, melhor o índice de qualidade e menor o custo por clique.' },
      { type: 'h2', text: '5. Use extensões' },
      { type: 'p', text: 'Sitelinks, chamada, localização e frases de destaque ocupam mais espaço e aumentam o clique sem custo extra. Não deixe de configurá-las.' },
      { type: 'h2', text: '6. O passo que ninguém pode pular: medir conversão' },
      { type: 'p', text: 'Sem acompanhamento de conversão, você voa no escuro. O mínimo é rastrear o lead; o ideal é saber quais cliques viraram venda lá no fim.' },
      { type: 'quote', text: 'Campanha sem medição de conversão é só uma forma elegante de gastar dinheiro.' },
      { type: 'p', text: 'No Althos CRM, o lead vindo do Google entra com a origem identificada e segue no funil até o fechamento. Assim você vê o retorno real de cada campanha, não só o custo por clique.' },
      { type: 'cta', text: 'Ligue seu Google Ads ao funil e veja o retorno de verdade.' },
    ],
  },
  {
    slug: 'google-ads-performance-max',
    title: 'Performance Max: vale a pena para o seu negócio?',
    description:
      'O que é Performance Max no Google Ads, como funciona a automação, quando faz sentido usar e os cuidados para não perder o controle da verba.',
    category: 'Google Ads',
    author: 'Equipe Althos',
    date: '2026-05-06',
    readingMinutes: 6,
    excerpt:
      'Performance Max promete automatizar tudo e entregar resultado. Mas a automação total tem armadilhas. Veja quando usar — e quando evitar.',
    blocks: [
      { type: 'p', text: 'Performance Max (PMax) é o tipo de campanha em que você fornece os criativos e a meta, e o Google distribui automaticamente por Pesquisa, Display, YouTube, Gmail e Maps. A promessa é máximo resultado com mínimo esforço. A realidade exige cuidado.' },
      { type: 'h2', text: 'Como funciona' },
      { type: 'p', text: 'Você sobe ativos (textos, imagens, vídeos) e define a conversão-alvo. A IA do Google decide onde, quando e para quem mostrar. Em troca de controle, você ganha alcance e automação.' },
      { type: 'h2', text: 'Quando faz sentido usar' },
      { type: 'ul', items: [
        'Quando já há histórico de conversões para a IA aprender.',
        'E-commerce com catálogo e volume.',
        'Para escalar depois de validar o que converte na Pesquisa.',
      ] },
      { type: 'h2', text: 'Quando ter cautela' },
      { type: 'ul', items: [
        'Contas novas, sem dados de conversão confiáveis.',
        'Orçamentos pequenos, onde a falta de controle pesa.',
        'Quando você ainda não sabe quais leads realmente viram venda.',
      ] },
      { type: 'h2', text: 'O risco da caixa-preta' },
      { type: 'p', text: 'A PMax otimiza para a conversão que você define. Se você marca "lead" como conversão, ela traz volume de leads — inclusive ruins. Sem qualidade de dado, a IA persegue a métrica errada.' },
      { type: 'quote', text: 'Automação é tão inteligente quanto o sinal de conversão que você dá a ela. Lead ruim ensina a IA a trazer mais lead ruim.' },
      { type: 'p', text: 'No Althos CRM, você identifica quais leads viram venda e alimenta o Google com o sinal certo. A PMax deixa de perseguir volume e passa a perseguir receita.' },
      { type: 'cta', text: 'Dê à automação do Google o sinal certo: vendas, não leads vazios.' },
    ],
  },
  {
    slug: 'google-ads-quanto-custa',
    title: 'Quanto custa anunciar no Google Ads? Entenda CPC, qualidade e ROI',
    description:
      'Quanto custa o Google Ads de verdade: como funciona o leilão, o que é CPC, índice de qualidade e como calcular o retorno real do investimento.',
    category: 'Google Ads',
    author: 'Equipe Althos',
    date: '2026-04-30',
    readingMinutes: 6,
    excerpt:
      'Não existe preço fixo no Google Ads — existe leilão. Entenda o que define seu custo por clique e como saber se o investimento está dando lucro.',
    blocks: [
      { type: 'p', text: 'A pergunta "quanto custa o Google Ads?" não tem resposta única porque o sistema funciona por leilão. O que você paga depende da concorrência pela palavra e da qualidade do seu anúncio.' },
      { type: 'h2', text: 'Como funciona o leilão' },
      { type: 'p', text: 'A cada busca, o Google calcula um ranking combinando seu lance com o índice de qualidade (relevância do anúncio, experiência da página e CTR esperado). Um anúncio melhor pode pagar menos e aparecer acima de um concorrente que deu um lance maior.' },
      { type: 'h2', text: 'O índice de qualidade reduz seu custo' },
      { type: 'ul', items: [
        'Anúncio relevante à busca: paga menos por clique.',
        'Página de destino coerente: melhora a experiência e a posição.',
        'Bom CTR histórico: o Google entende que seu anúncio responde à intenção.',
      ] },
      { type: 'h2', text: 'CPC importa menos que custo por venda' },
      { type: 'p', text: 'Focar só no custo por clique engana. Uma palavra cara que converte muito pode ser mais lucrativa que uma barata que não vende. O número que decide é o custo por venda — e o retorno (ROI) que ele gera.' },
      { type: 'quote', text: 'Clique barato que não vende é caro. Clique caro que vende é barato.' },
      { type: 'p', text: 'No Althos CRM, você acompanha o lead do clique até o fechamento e calcula o ROI real por campanha e por palavra-chave. Assim, decide onde investir com base em lucro, não em CPC.' },
      { type: 'cta', text: 'Calcule o ROI real das suas campanhas, do clique à venda.' },
    ],
  },
  {
    slug: 'google-ads-remarketing-recuperar-visitantes',
    title: 'Remarketing no Google Ads: recupere quem visitou e não comprou',
    description:
      'Como usar o remarketing no Google Ads para reimpactar visitantes: listas de público, Display, YouTube e RLSA na Pesquisa para fechar mais vendas.',
    category: 'Google Ads',
    author: 'Equipe Althos',
    date: '2026-04-22',
    readingMinutes: 5,
    excerpt:
      'A maior parte de quem visita seu site vai embora sem comprar. O remarketing do Google traz essas pessoas de volta — em vários formatos.',
    blocks: [
      { type: 'p', text: 'Pouca gente compra na primeira visita. O remarketing do Google permite reimpactar quem já passou pelo seu site, em diferentes canais, lembrando-os da sua solução no momento certo.' },
      { type: 'h2', text: 'Formatos de remarketing' },
      { type: 'ul', items: [
        'Display: banners que seguem o visitante por sites e apps.',
        'YouTube: vídeos para quem já demonstrou interesse.',
        'RLSA: ajustar lances na Pesquisa para quem já visitou.',
      ] },
      { type: 'h2', text: 'Segmente por comportamento' },
      { type: 'p', text: 'Quem visitou a página de preços está mais quente do que quem viu só o blog. Crie listas por páginas visitadas e por tempo desde a visita, e adapte a mensagem ao nível de interesse.' },
      { type: 'h2', text: 'Não canse o público' },
      { type: 'p', text: 'Limite a frequência e renove os anúncios. Remarketing repetitivo demais vira incômodo e mancha a marca.' },
      { type: 'quote', text: 'O remarketing traz a pessoa de volta. O atendimento rápido e o follow-up fecham a conta.' },
      { type: 'p', text: 'No Althos CRM, o visitante que voltou e virou lead é atendido na hora e entra no funil com follow-up. O anúncio reabre a porta; o processo conduz até a venda.' },
      { type: 'cta', text: 'Traga os visitantes de volta e conduza-os até a venda.' },
    ],
  },
  // ─── FUNIL DE VENDAS ───────────────────────────────────────────────────────
  {
    slug: 'funil-vendas-follow-up-automatico',
    title: 'Follow-up automático: a venda está no acompanhamento',
    description:
      'Por que a maioria das vendas exige vários contatos e como montar um follow-up automático no funil para parar de perder negócios por esquecimento.',
    category: 'Funil de Vendas',
    author: 'Equipe Althos',
    date: '2026-05-19',
    readingMinutes: 6,
    excerpt:
      'A maioria das vendas acontece depois do quinto contato. O problema: quase ninguém faz follow-up suficiente. A solução é automatizar.',
    blocks: [
      { type: 'p', text: 'Existe um abismo entre o número de contatos que uma venda costuma exigir e o número que os vendedores realmente fazem. A maioria desiste cedo demais — e é exatamente aí que o dinheiro escapa. A solução é tornar o follow-up um processo, não uma lembrança.' },
      { type: 'h2', text: 'Por que o follow-up falha' },
      { type: 'ul', items: [
        'O vendedor esquece (volume de leads alto).',
        'Acha que insistir é "incomodar".',
        'Não tem um sistema lembrando quem retornar e quando.',
      ] },
      { type: 'h2', text: 'A estrutura de uma cadência de follow-up' },
      { type: 'ol', items: [
        'Contato 1: resposta imediata ao lead (minutos, não horas).',
        'Contato 2: no mesmo dia ou no dia seguinte, agregando valor.',
        'Contato 3 a 5: espaçados, com provas, casos e quebra de objeções.',
        'Reativação: para quem não respondeu, em 30/60/90 dias.',
      ] },
      { type: 'h2', text: 'Automatize sem perder o toque humano' },
      { type: 'p', text: 'Nem todo follow-up precisa ser manual. Lembretes automáticos, mensagens programadas e tarefas geradas pelo sistema garantem que ninguém caia no esquecimento — e liberam o vendedor para o contato que realmente exige atenção humana.' },
      { type: 'quote', text: 'Não é falta de leads que derruba as vendas. É falta de acompanhamento.' },
      { type: 'p', text: 'No Althos CRM, leads parados disparam alertas, follow-ups são programados por etapa e a IA pode dar o primeiro retorno na hora. O acompanhamento deixa de depender da memória do vendedor.' },
      { type: 'cta', text: 'Nunca mais perca uma venda por esquecer de retornar.' },
    ],
  },
  {
    slug: 'funil-vendas-qualificacao-bant',
    title: 'Qualificação de leads: o método BANT explicado na prática',
    description:
      'Como qualificar leads com o método BANT (orçamento, autoridade, necessidade e prazo) para focar o time no que fecha e parar de perder tempo com curioso.',
    category: 'Funil de Vendas',
    author: 'Equipe Althos',
    date: '2026-05-13',
    readingMinutes: 6,
    excerpt:
      'Atender todo lead igual é desperdício. O método BANT ajuda a separar quem está pronto para comprar de quem só está pesquisando.',
    blocks: [
      { type: 'p', text: 'Nem todo lead merece o mesmo esforço. Tentar fechar com quem não tem perfil, verba ou poder de decisão consome o tempo que deveria ir para quem está pronto. O BANT é um filtro simples para priorizar.' },
      { type: 'h2', text: 'O que significa BANT' },
      { type: 'ul', items: [
        'Budget (orçamento): a pessoa tem condições de pagar?',
        'Authority (autoridade): ela decide ou influencia a compra?',
        'Need (necessidade): existe uma dor real que você resolve?',
        'Timing (prazo): a decisão é para agora ou para "algum dia"?',
      ] },
      { type: 'h2', text: 'Como aplicar na conversa' },
      { type: 'p', text: 'Você não precisa de um interrogatório. Perguntas naturais revelam o BANT: "como vocês resolvem isso hoje?", "quem mais participa dessa decisão?", "para quando você precisa disso resolvido?". As respostas dizem o quão quente é o lead.' },
      { type: 'h2', text: 'Nem todo lead frio deve ser descartado' },
      { type: 'p', text: 'Um lead com necessidade clara, mas sem prazo, não está perdido — está para nutrição. Em vez de jogá-lo fora, coloque-o numa cadência de acompanhamento até o momento amadurecer.' },
      { type: 'quote', text: 'Qualificar não é dispensar leads — é decidir a quem dar atenção agora e a quem nutrir para depois.' },
      { type: 'p', text: 'No Althos CRM, você marca o nível de qualificação de cada lead, prioriza os quentes no funil e mantém os mornos numa cadência automática. O time foca onde a venda está mais perto.' },
      { type: 'cta', text: 'Foque o time nos leads que realmente vão fechar.' },
    ],
  },
]
